# Projeto I - Computação Centífica II
### Solução de EDOs
> Autor: Gil Miranda<br>
> Contato: gil.neto@ufrj.br<br>
> Repo: [@mirandagil](https://github.com/mirandagil)<br>

In [45]:
import numpy as np
import matplotlib.pyplot as plt

### Encontrando a solução da EDO

$$\frac{\mathrm{d}u}{\mathrm{d}t} = Au + b$$
Como é uma equação separável, podemos resolver da seguinte forma:
$$
\begin{align}
\frac{\mathrm{d}u}{Au + b} &= \mathrm{d}t\\
\int \frac{\mathrm{d}u}{Au + b} &= \int \mathrm{d}t\\
ln(Au+b)&= A(t+c)\\
Au &= C_0 e^{At} - b\\
u &= \frac{C_0 e^{At}}{A} - \frac{b}{A}\\
\text{Mas como A é uma matriz, a solução terá a forma}\\
u(t) &= A^{-1} C_0 e^{At} - A^{-1} b\\
\text{Para descobrirmos $C_0$}\\
u(0) &= A^{-1} C_0 e^{0} - A^{-1} b\\
C_0 &= Au_0 + b
\end{align}
$$

### Verificando sanidade das matrizes

In [138]:
def verifica_defeituosa(A): ## input: A -> Matriz
    def cauchy_schwarz(u,v): ## input: u - vetor nx1, v -> vetor nx1
        norm_u = np.linalg.norm(u)
        norm_v = np.linalg.norm(v)
        scalar_product = np.dot(u,v)
        if abs(scalar_product) == abs(norm_u * norm_v):
            return 1
        else:
            return 0

    M_eigen_vects = np.linalg.eig(A)[1] ## Retorna a matriz de autovetores em forma de coluna
    eigen_vects = [M_eigen_vects[:,i] for i in range(0,M_eigen_vects.shape[1])] ## Retorna cada autovetor como um vetor linha
    for i in range(0, len(eigen_vects)):
        for j in range(1,len(eigen_vects)):
            if i != j:
                if cauchy_schwarz(eigen_vects[i],eigen_vects[j]):
                    return 1
                    break
    return 0

Caso matriz diagonalizavel
$$e^{At} = S^{-1} \Lambda S$$

In [137]:
def e_to_diag(A, t):
    eigen = np.linalg.eig(A) 
    M_eigen_vects = eigen[1] ## Retorna a matriz de autovetores em forma de coluna
    eigen_values= eigen[0]
    diag_A = np.diag(eigen_values)
    inv_M = np.linalg.inv(M_eigen_vects)
    return inv_M * np.e**(diag_A*t) * M_eigen_vects

Caso matriz defeituosa
$$
e^{At} = I + \frac{At}{1!} + \frac{A^2t^2}{2!} +\frac{A^3t^3}{3} +\frac{A^4t^4}{4!} + \dots
$$

In [ ]:
def e_to_defect(A, t, termo = 10):
    I = np.identity(2)
    e_to = I
    for i in range(1,termo):
        e_to += np.linalg.matrix_power(A*t, i)/np.math.factorial(i)
    return e_to

In [139]:
def ed_solver(A, b, c, t):
    is_defect = verifica_defeituosa(A)
    if is_defect:
        e_to_A = e_to_defect(A, t)
    else:
        e_to_A = e_to_diag(A,t)
        
    u_n = np.linalg.inv(A)*c*e_to_A - np.linalg.inv(A)*b

In [ ]:
ed_solver()

In [150]:
A = np.array([[3,1],[7,2]])

def cauchy_schwarz(u,v): ## input: u - vetor nx1, v -> vetor nx1
    norm_u = np.linalg.norm(u)
    norm_v = np.linalg.norm(v)
    scalar_product = np.dot(u,v)
    if abs(scalar_product) == abs(norm_u * norm_v):
        return 1
    else:
        return 0
    
M_eigen_vects = np.linalg.eig(A)[1] ## Retorna a matriz de autovetores em forma de coluna
eigen_vects = [M_eigen_vects[:,i] for i in range(0,M_eigen_vects.shape[1])] ## Retorna cada autovetor como um vetor linha
for i in range(0, len(eigen_vects)):
    for j in range(1,len(eigen_vects)):
        if i != j:
            if cauchy_schwarz(eigen_vects[i],eigen_vects[j]):
                print('foi')

In [48]:
B = np.array([[-1,0,0],[1,-1,0],[0,1,-1]])

In [49]:
verifica_defeituosa(B)
# cauchy_schwarz(B[0],B[2])

1

In [50]:
eigen_vects[0].dot(eigen_vects[1])

0.0

In [152]:
# A = np.array([[1,0],[0,1]])
e_to_diag(A,2)

array([[ 1.91938849e+04, -1.33760345e-01],
       [-1.23932860e+00,  4.03337095e-01]])

In [153]:
e_to_defect(A,2)

array([[ 7884.35661376,  2469.37283951],
       [17285.60987654,  5414.98377425]])

In [136]:
np.e**2

7.3890560989306495

In [151]:
np.linalg.eig(A)

(array([ 5.1925824, -0.1925824]), array([[ 0.41496214, -0.29890615],
        [ 0.90983868,  0.95428251]]))