# Implementando `numpy.linalg.solve()`

Vamos implementar a nossa própria versão de "solve".
A principal razão para fazê-lo é que a versão do `numpy` não é "genérica", ou seja,
ela não funciona para uma matriz qualquer, mas apenas para matrizes de números.
E poderíamos ter um sistema linear cujos coeficientes não fossem números.

Por exemplo, imagine que queremos resolver o seguinte sistema:
$$\begin{align*}
e^t x + e^{-t}y + \ e^{3t} z & = 2 \\
e^t x - e^{-t}y + 3e^{3t} z& = -1 \\
e^t x + e^{-t}y + 9e^{3t} z& = 1
\end{align*}$$
As variáveis $x$ e $y$ são **funções** de $t$,
mas o mais importante é que este é um _sistema linear_ em $t$,
logo podemos aplicar a mesma ideia da eliminação de Gauss!

## Eliminação

Para resolver um sistema linear, procedemos em duas etapas.
A primeira é conhecida como "eliminação de Gauss", que vai eliminando sucessivamente os coeficientes.

In [1]:
import numpy as np

In [2]:
def elim(A,b, debug=False):
    """Elimina as equações do sistema Ax = b, de cima para baixo.
    Os dados de entrada são _alterados_ pela execução da função, para refletir o novo sistema."""
    m,n = np.shape(A)
    ### Resposta aqui


In [3]:
A = [[1,2,3],[4,5,6],[7,8,9]]
A, np.shape(A)

([[1, 2, 3], [4, 5, 6], [7, 8, 9]], (3, 3))

In [4]:
b = [1,3,3]

In [5]:
elim(A,b, debug=True)

0
[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
[1, 3, 3]

1
[[1, 2, 3], [0, -3.0, -6.0], [0, -6.0, -12.0]]
[1, -1.0, -4.0]

2
[[1, 2, 3], [0, -3.0, -6.0], [0, 0, 0.0]]
[1, -1.0, -2.0]

end
[[1, 2, 3], [0, -3.0, -6.0], [0, 0, 0.0]]
[1, -1.0, -2.0]



In [6]:
A, b

([[1, 2, 3], [0, -3.0, -6.0], [0, 0, 0.0]], [1, -1.0, -2.0])

In [7]:
A = np.random.rand(4,4)
b = np.random.rand(4)
elim(A,b)

In [8]:
A = np.random.rand(3,4)
b = np.random.rand(3)
elim(A,b)

In [9]:
A = np.random.rand(4,3)
b = np.random.rand(4)
elim(A,b)

## Substituição

A segunda etapa consiste em resolver "de fato" o sistema, de baixo para cima.
Como encontramos as soluções e vamos substituindo os valores nas respectivas equações,
este etapa se chama substituição.

In [10]:
def subst(A,b):
    """Substitui as equações do sistema Ax = b, de baixo para cima,
    e retorna o vetor x das soluções, sem alterar A nem b."""
    m,n = np.shape(A)
    # Verifique que a matriz A está correta
    ### Resposta aqui


In [11]:
A = np.random.rand(4,4)
b = np.random.rand(4)
elim(A,b)
subst(A,b)

[1.4310965894808454,
 0.61839150518035457,
 -1.1122299978888677,
 -0.16541226490125571]

In [12]:
np.dot(A,_)

array([ 0.96897068, -0.16287873, -2.36653882,  0.10070464])

### Exercício

Um dos maiores problemas do nosso código de eliminação é que ele modifica a matriz.
Isso é ruim para verificar se a solução encontrada pela substituição satisfaz a equação original.
(Podemos verificar que satisfaz o sistema "eliminado", pois a substituição não modifica $A$ ou $b$).

Corrija isso, e verifique que o procedimento duplo (eliminação + substituição)
de fato encontra uma solução.

In [13]:
def elim(A,b, debug=False):
    """Elimina as equações do sistema Ax = b, de cima para baixo,
    retornando (U,b') correspondentes ao sistema triangular superior Ux = b', sem alterar as matrizes A e b."""
    m,n = np.shape(A)
    U = np.copy(A)
    b_ = np.copy(b)
    ### Resposta aqui


In [14]:
A = np.random.rand(4,4)
b = np.random.rand(4)
U, b_ = elim(A,b)
x = subst(U,b_)
# deveria dar bem perto de zero!
np.dot(A,x) - b

array([  0.00000000e+00,   2.22044605e-16,  -3.33066907e-16,
         2.22044605e-16])

In [15]:
def solve(A,b):
    U,b_ = elim(A,b)
    return subst(U,b_)

In [16]:
x1 = solve(A,b)
x2 = np.linalg.solve(A,b)
x1 - x2

array([  3.99680289e-15,  -1.30451205e-15,   5.55111512e-16,
        -2.66453526e-15])

In [17]:
np.dot(A,x1) - b, np.dot(A,x2) - b

(array([  0.00000000e+00,   2.22044605e-16,  -3.33066907e-16,
          2.22044605e-16]),
 array([ -1.11022302e-16,   1.11022302e-16,  -1.11022302e-16,
          0.00000000e+00]))

# Aplicação: sistemas racionais

In [18]:
from fractions import Fraction

In [19]:
A = [[3,2,3],[4,7,6],[7,8,7]]
b = [1,2,1]

In [20]:
AF = [[Fraction(aij) for aij in ai] for ai in A]
bF = [Fraction(bi) for bi in b]

In [21]:
elim(AF, bF, debug=True)

0
[[Fraction(3, 1) Fraction(2, 1) Fraction(3, 1)]
 [Fraction(4, 1) Fraction(7, 1) Fraction(6, 1)]
 [Fraction(7, 1) Fraction(8, 1) Fraction(7, 1)]]
[Fraction(1, 1) Fraction(2, 1) Fraction(1, 1)]

1
[[Fraction(3, 1) Fraction(2, 1) Fraction(3, 1)]
 [0 Fraction(13, 3) Fraction(2, 1)]
 [0 Fraction(10, 3) Fraction(0, 1)]]
[Fraction(1, 1) Fraction(2, 3) Fraction(-4, 3)]

2
[[Fraction(3, 1) Fraction(2, 1) Fraction(3, 1)]
 [0 Fraction(13, 3) Fraction(2, 1)]
 [0 0 Fraction(-20, 13)]]
[Fraction(1, 1) Fraction(2, 3) Fraction(-24, 13)]

end
[[Fraction(3, 1) Fraction(2, 1) Fraction(3, 1)]
 [0 Fraction(13, 3) Fraction(2, 1)]
 [0 0 Fraction(-20, 13)]]
[Fraction(1, 1) Fraction(2, 3) Fraction(-24, 13)]



(array([[Fraction(3, 1), Fraction(2, 1), Fraction(3, 1)],
        [0, Fraction(13, 3), Fraction(2, 1)],
        [0, 0, Fraction(-20, 13)]], dtype=object),
 array([Fraction(1, 1), Fraction(2, 3), Fraction(-24, 13)], dtype=object))

In [22]:
solve(AF, bF)

[Fraction(-3, 5), Fraction(-2, 5), Fraction(6, 5)]

In [23]:
np.linalg.solve(A,b)

array([-0.6, -0.4,  1.2])

In [24]:
np.linalg.solve(AF,bF)

TypeError: No loop matching the specified signature and casting
was found for ufunc solve1