![CC-BY-SA](https://mirrors.creativecommons.org/presskit/buttons/88x31/svg/by-sa.svg)
This notebook was created by [Bernardo Freitas Paulo da Costa](http://www.im.ufrj.br/bernardofpc),
and is licensed under Creative Commons BY-SA

In [1]:
import numpy as np
import matplotlib.pyplot as plt

# O método de Newton em dimensão maior

A ideia de "seguir a tangente" para
- aproximar a função $f$
- e com isso achar um zero "mais rápido"

pode ser generalizada para qualquer dimensão (até infinita!).

Antes de mais nada, vejamos o que quer dizer encontrar uma raiz em 2-D.

### Exercício: Equações e raízes

Imagine que temos uma função $f : R^2 \to R$, representando uma equação $f(x) = 0$.
Por exemplo, pense na função $f(x,y) = x^2 - y$.
Quais são as raízes de $f$?
Quantas são?

## O método de Newton

Lembre-se que o passo de Newton é dado por $f(x)/f'(x)$.
A derivada de $f:R^2 \to R$ pode ser dada por um vetor (o gradiente).
Não faz muito sentido dividir um escalar $f(x)$ por um vetor...

Assim, a generalização do método de Newton
necessita que $f'(x)$ seja uma matriz quadrada (para podermos "dividir").
Isso acontece quando $f: R^n \to R^n$;
neste caso, $f(x)$ é um vetor, e de fato (ainda bem!) faz sentido dividir um vetor por uma matriz.

### Exercício

O que quer dizer, neste caso, encontrar uma raiz de $f$??

## Prática

Agora, temos que programar uma função $f$ que receba um vetor, e retorne um vetor.
Imagine que queremos programar a seguinte função:

$$ f(x,y) = \big(x^2 - 2y^3 + 3xy, \cos(x) + \sin(y)\big). $$
 
Como escrever isso no computador?

In [2]:
def f(x,y):
    ### Resposta aqui


### Exercício

Em que sentido esta função é "vetorial"?

In [3]:
### Resposta aqui


(array([  3.20000000e+01,   2.81580000e+01,   2.46240000e+01,
          2.13860000e+01,   1.84320000e+01,   1.57500000e+01,
          1.33280000e+01,   1.11540000e+01,   9.21600000e+00,
          7.50200000e+00,   6.00000000e+00,   4.69800000e+00,
          3.58400000e+00,   2.64600000e+00,   1.87200000e+00,
          1.25000000e+00,   7.68000000e-01,   4.14000000e-01,
          1.76000000e-01,   4.20000000e-02,   1.26217745e-29,
          3.80000000e-02,   1.44000000e-01,   3.06000000e-01,
          5.12000000e-01,   7.50000000e-01,   1.00800000e+00,
          1.27400000e+00,   1.53600000e+00,   1.78200000e+00,
          2.00000000e+00,   2.17800000e+00,   2.30400000e+00,
          2.36600000e+00,   2.35200000e+00,   2.25000000e+00,
          2.04800000e+00,   1.73400000e+00,   1.29600000e+00,
          7.22000000e-01,  -2.84217094e-14,  -8.82000000e-01,
         -1.93600000e+00,  -3.17400000e+00,  -4.60800000e+00,
         -6.25000000e+00,  -8.11200000e+00,  -1.02060000e+01,
        

In [4]:
### Resposta aqui


(2, 50, 50)

## Uma nova interface

Para sempre passarmos "um ponto" pelo método de Newton, precisamos "desconstruir" os argumentos de `f`.

In [5]:
def f(v):
    x,y = v
    return (x**2 - 2*y**3 + 3*x*y, np.cos(x) + np.sin(y))

### Exercício

Agora, implemente a derivada

In [6]:
def df(v):
    ### Resposta aqui


### Exercício

Estas funções continuam vetoriais?  Em que sentido?

In [7]:
np.shape(df([Xs, Ys]))

(2, 2, 50, 50)

## O algoritmo

Agora que sabemos calcular o passo matematicamente, só precisamos:
- adaptar o critério de parada
- calcular numericamente o passo

In [8]:
def newton_list(f, df, x, abstol=1e-8, reltol=1e-8, ytol=1e-8, maxiter=100):
    fx = f(x)
    if np.linalg.norm(fx) < ytol:
        return [x]
    step = np.linalg.solve(df(x), fx)
    newx = x - step
    if maxiter == 0:
        return [newx]
    if np.linalg.norm(step) < abstol or np.linalg.norm(step) < reltol*np.linalg.norm(x):
        return [newx]

    return [x] + newton_list(f, df, newx, abstol, reltol, ytol, maxiter-1)

In [9]:
newton_list(f, df, [1,1])

[[1, 1],
 array([-28.50856316, -47.51427194]),
 array([-99.32635853, -30.38104147]),
 array([-91.21395802, -17.93223128]),
 array([-52.8207729 , -10.81007523]),
 array([-50.49040323,  -3.00681873]),
 array([-32.03497638,   1.99508323]),
 array([-30.64584916,   8.14518789]),
 array([-27.38834407,   6.08293195]),
 array([-25.14231496,   5.15621071]),
 array([-24.39741321,   4.91408273]),
 array([-24.73887666,   4.95927761]),
 array([-24.8484647,   4.9764188]),
 array([-24.86554244,   4.97906911]),
 array([-24.86599109,   4.97913876]),
 array([-24.8659914 ,   4.97913881])]

In [10]:
f(_[-1])

(5.6843418860808015e-14, -4.496403249731884e-14)

In [11]:
newton_list(f, df, [2,2])

[[2, 2],
 array([ 2.43240234,  2.24022352]),
 array([ 2.46480906,  2.24696598]),
 array([ 2.46518405,  2.24720488]),
 array([ 2.46518409,  2.24720489])]

In [12]:
f(_[-1])

(0.0, 6.6613381477509392e-16)

# Atenção:

É muito importante que a derivada esteja calculada corretamente, senão pode dar bastante errado.
Em particular, as derivadas cruzadas devem estar corretamente colocadas:

$$ \begin{bmatrix}
\frac{\partial f_1(v)}{\partial x_1} & \frac{\partial f_1(v)}{\partial x_2} \\
\frac{\partial f_2(v)}{\partial x_1} & \frac{\partial f_2(v)}{\partial x_2}
\end{bmatrix} $$

In [13]:
### Resposta aqui


In [14]:
newton_list(f, df_errada, [2,2], maxiter=15)

/usr/lib64/python3.4/site-packages/ipykernel_launcher.py:3: RuntimeWarning: overflow encountered in double_scalars
  This is separate from the ipykernel package so we can avoid doing imports until
/usr/lib64/python3.4/site-packages/ipykernel_launcher.py:3: RuntimeWarning: invalid value encountered in double_scalars
  This is separate from the ipykernel package so we can avoid doing imports until
/usr/lib64/python3.4/site-packages/ipykernel_launcher.py:3: RuntimeWarning: invalid value encountered in cos
  This is separate from the ipykernel package so we can avoid doing imports until
/usr/lib64/python3.4/site-packages/ipykernel_launcher.py:3: RuntimeWarning: invalid value encountered in sin
  This is separate from the ipykernel package so we can avoid doing imports until
/usr/lib64/python3.4/site-packages/ipykernel_launcher.py:4: RuntimeWarning: invalid value encountered in double_scalars
  after removing the cwd from sys.path.
/usr/lib64/python3.4/site-packages/ipykernel_launcher.py:4:

[[2, 2],
 array([ 2.02184346,  2.24022352]),
 array([ 2.1382931 , -1.71101269]),
 array([ 1.94510041,  2.77166898]),
 array([  2.37690026, -15.87713326]),
 array([ -5.40849471e+00,   1.18731836e+04]),
 array([  2.31113002e+03,  -4.36244660e+12]),
 array([ -9.52898635e+11,  -1.88048045e+38]),
 array([  1.02786929e+037,  -1.65982096e+115]),
 array([-inf,  inf]),
 array([ nan,  nan]),
 array([ nan,  nan]),
 array([ nan,  nan]),
 array([ nan,  nan]),
 array([ nan,  nan]),
 array([ nan,  nan])]